export const supriseMePrompts = [
    "A flower bloomed in the garden.",
    "A lone tree stood tall in the middle of the field.",
    "The ocean waves crashed against the rocky shore.",
    "A rainbow arced across the sky after the rain.",
    "A hot air balloon floated gracefully in the clear blue sky.",
    "A beautiful sunset painted the sky with shades of pink and orange.",
    "A mountain range stood tall and majestic in the distance.",
    "The leaves rustled in the wind as autumn approached.",
    "A meadow was filled with colorful wildflowers.",
    "The moon shone brightly in the starry night sky.",
    "The aurora borealis lit up the sky with vibrant colors.",
    "A waterfall cascaded down the rocky cliff.",
    "A flock of seagulls flew overhead, squawking loudly.",
    "A butterfly landed delicately on a flower petal.",
    "A city skyline glowed brightly at night.",
    "The sunflowers swayed gently in the breeze.",
    "A boat sailed peacefully on the calm lake.",
    "A snow-capped mountain peak loomed in the distance.",
    "A forest was alive with the sounds of chirping birds and rustling leaves.",
    "The night sky was filled with twinkling stars.",
    "A field of wheat swayed in the gentle breeze.",
    "A deer grazed peacefully in the meadow.",
    "The Milky Way galaxy stretched across the night sky.",
    "A lighthouse stood tall on the rocky coast, shining its light into the darkness.",
    "A river flowed calmly through the lush green landscape.",
    "A vineyard was filled with rows of ripening grapes.",
    "The Eiffel Tower loomed majestically in the distance.",
    "The desert was a sea of sand and heat.",
    "A bird perched on a tree branch, singing a sweet melody.",
    "The Grand Canyon was a breathtaking sight to behold.",
    "The sun set behind the mountains, casting long shadows over the valley.",
    "A lake sparkled in the sunlight, surrounded by towering trees.",
    "A rainbow trout leaped out of the water, glistening in the sun.",
    "A starry night sky was reflected in the calm waters of the lake.",
    "The Great Barrier Reef teemed with colorful fish and vibrant coral.",
    "The sun rose slowly over the horizon, painting the sky with hues of orange and pink.",
    "A polar bear roamed the frozen tundra, looking for food.",
    "The Golden Gate Bridge spanned the bay, connecting the city to the other side.",
    "A garden was filled with a variety of flowers, each with its own unique beauty.",
    "The Louvre Museum was filled with priceless works of art from around the world.",
    "A hot air balloon festival filled the sky with colorful shapes and designs.",
    "The Parthenon stood proudly atop the hill, a testament to ancient Greek civilization.",
    "A castle sat on a hill, surrounded by a moat and towering walls.",
    "The Roman Colosseum was a marvel of ancient engineering and architecture.",
    "A hummingbird flitted from flower to flower, sipping nectar along the way.",
    "The Sydney Opera House was a masterpiece of modern architecture.",
    "A peacock strutted proudly, displaying its colorful plumage.",
    "The Taj Mahal was a stunning monument to love and beauty.",
    "The Great Wall of China snaked across the landscape, a testament to human ingenuity.",
    "A rainbow appeared after the storm, filling the sky with vibrant colors.",
    "The Acropolis was a symbol of ancient Athens' power and glory.",
    "A herd of elephants roamed the savannah, kicking up dust as they went.",
    "The Washington Monument towered over the National Mall, a tribute to America's first president.",
    "A butterfly garden was filled with delicate creatures flitting from flower to flower.",
    "The Colosseum was a site of ancient gladiatorial battles and spectacles.",
    "A tulip field was a sea of color, with rows of red, yellow, and pink flowers stretching out as far",
]    